# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16b99ac1f97425780b0826229ed31a0863bced4d2dbd3366e43c3233032e62273bf1dcef2d86c5db5b23b3040fec5419fff729cfe31d27dae74920535e9d2ece

test:
  secret_key_base: 185083387cecedcb8063c7311f8f215b10f52d8cee6a498f64bc3052661b4c3aeeec5b1d71758d46ec0ac4864ef3ec4bb3594ff00414a19b42be5fa5f46927fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
